FROM node:12.16.1

LABEL version="1.0"
LABEL description="This is the base docker image for frontend react app odmanagement."
LABEL maintainer = ["samyukth2310@gmail.com"]

WORKDIR /ODMANAGEMENT

COPY ["package.json", "package-lock.json", "./"]

RUN npm install --production

COPY . .

EXPOSE 3000

CMD ["npm", "start"]